# CORES GERAIS DA APLICAÇÃO
APP_BG = "#F5F5F5"
APP_TEXT = "#212121"
SHADOW_COLOR = "#1F000000"

# SIDEBAR
SIDEBAR_BG = "#FFFFFF"
SIDEBAR_LINK_ACTIVE_BG = "#EEF0F8"
SIDEBAR_LINK_ACTIVE_TEXT = "#3949AB"
SIDEBAR_LINK_HOVER_BG = "#E8EAF6"
SIDEBAR_LINK_HOVER_TEXT = "#3949AB"
SIDEBAR_LINK_TEXT = "#616161"
SIDEBAR_THEME_TOGGLE_BG = "#F5F5F5"
SIDEBAR_THEME_TOGGLE_ICON = "#FFCA28"
SIDEBAR_TITLE_TEXT = "#3F51B5"

# HEADER
HEADER_BG = "#FFFFFF"
HEADER_TITLE_TEXT = "#212121"

# CAMPOS DE BUSCA
SEARCH_BG = "#F5F5F5"
SEARCH_FOCUS_RING = "#3F51B5"
SEARCH_ICON = "#BDBDBD"

# ABAS (TABBAR/TABS)
TAB_ACTIVE_BORDER = "#3F51B5"
TAB_ACTIVE_TEXT = "#3949AB"
TABS_BORDER_BOTTOM = "#EEEEEE"
TABS_HOVER_TEXT = "#616161"
TABS_TEXT = "#9E9E9E"

# TABELAS / CARDS DE REGISTROS
CARD_BG = "#FFFFFF"
CARD_TITLE_TEXT = "#212121"
TABLE_DIVIDER = "#EEEEEE"
TABLE_EMPTY_TEXT = "#9E9E9E"
TABLE_HEADER_BG = "#FAFAFA"
TABLE_HEADER_BORDER_BOTTOM = "#EEEEEE"
TABLE_HEADER_TEXT = "#9E9E9E"
TABLE_ROW_NUMBER_TEXT = "#212121"
TABLE_ROW_TEXT = "#9E9E9E"

# BADGES DE STATUS
BADGE_A_VENCER_BG = "#FFF9C4"
BADGE_A_VENCER_TEXT = "#F9A825"
BADGE_VENCIDA_BG = "#FFCDD2"
BADGE_VENCIDA_TEXT = "#C62828"
BADGE_VIGENTE_BG = "#C8E6C9"
BADGE_VIGENTE_TEXT = "#2E7D32"

# BOTÕES DE AÇÃO
BTN_DELETE_ICON = "#E53935"
BTN_DELETE_ICON_HOVER = "#B71C1C"
BTN_EDIT_ICON = "#757575"
BTN_EDIT_ICON_HOVER = "#212121"
BTN_NOVA_ATA_BG = "#3949AB"
BTN_NOVA_ATA_HOVER_BG = "#303F9F"
BTN_NOVA_ATA_TEXT = "#FFFFFF"
BTN_VIEW_ICON = "#3949AB"
BTN_VIEW_ICON_HOVER = "#1A237E"

__all__ = [name for name in globals() if name.isupper()]
