import flet as ft

LIGHT = {
    "background": ft.colors.GREY_100,
    "text": ft.colors.GREY_900,
    "sidebar_bg": ft.colors.WHITE,
    "sidebar_title": ft.colors.INDIGO_500,
    "sidebar_link": ft.colors.GREY_700,
    "sidebar_hover_bg": ft.colors.INDIGO_100,
    "sidebar_hover_text": ft.colors.INDIGO_600,
    "sidebar_active_bg": ft.colors.INDIGO_50,
    "sidebar_active_text": ft.colors.INDIGO_600,
    "sidebar_toggle_bg": ft.colors.GREY_100,
    "toggle_sun": ft.colors.AMBER_400,
    "toggle_moon": ft.colors.GREY_500,
    "header_bg": ft.colors.WHITE,
    "header_title": ft.colors.GREY_900,
    "search_bg": ft.colors.GREY_100,
    "search_text": ft.colors.GREY_900,
    "search_icon": ft.colors.GREY_400,
    "search_focus_border": ft.colors.INDIGO_500,
    "new_button_bg": ft.colors.INDIGO_600,
    "new_button_hover": ft.colors.INDIGO_700,
    "new_button_text": ft.colors.WHITE,
    "tabs_border": ft.colors.GREY_200,
    "tabs_text": ft.colors.GREY_500,
    "tabs_hover_text": ft.colors.GREY_700,
    "tab_active_border": ft.colors.INDIGO_500,
    "tab_active_text": ft.colors.INDIGO_600,
    "table_bg": ft.colors.WHITE,
    "table_title": ft.colors.GREY_900,
    "table_header_border": ft.colors.GREY_200,
    "table_header_bg": ft.colors.GREY_50,
    "table_header_text": ft.colors.GREY_500,
    "table_text_number": ft.colors.GREY_900,
    "table_text_other": ft.colors.GREY_500,
    "table_divider": ft.colors.GREY_200,
    "table_empty": ft.colors.GREY_500,
    "badge_vigente_bg": ft.colors.GREEN_100,
    "badge_vigente_text": ft.colors.GREEN_800,
    "badge_a_vencer_bg": ft.colors.YELLOW_100,
    "badge_a_vencer_text": ft.colors.YELLOW_800,
    "badge_vencida_bg": ft.colors.RED_100,
    "badge_vencida_text": ft.colors.RED_800,
    "view_icon": ft.colors.INDIGO_600,
    "view_hover_icon": ft.colors.INDIGO_900,
    "edit_icon": ft.colors.GREY_600,
    "edit_hover_icon": ft.colors.GREY_900,
    "delete_icon": ft.colors.RED_600,
    "delete_hover_icon": ft.colors.RED_900,
}

DARK = {
    "background": ft.colors.GREY_900,
    "text": ft.colors.WHITE,
    "sidebar_bg": ft.colors.GREY_800,
    "sidebar_title": ft.colors.INDIGO_500,
    "sidebar_link": ft.colors.GREY_300,
    "sidebar_hover_bg": ft.colors.INDIGO_900,
    "sidebar_hover_text": ft.colors.INDIGO_300,
    "sidebar_active_bg": ft.colors.INDIGO_900,
    "sidebar_active_text": ft.colors.INDIGO_300,
    "sidebar_toggle_bg": ft.colors.GREY_700,
    "toggle_sun": ft.colors.AMBER_400,
    "toggle_moon": ft.colors.GREY_500,
    "header_bg": ft.colors.GREY_800,
    "header_title": ft.colors.WHITE,
    "search_bg": ft.colors.GREY_700,
    "search_text": ft.colors.WHITE,
    "search_icon": ft.colors.GREY_400,
    "search_focus_border": ft.colors.INDIGO_500,
    "new_button_bg": ft.colors.INDIGO_600,
    "new_button_hover": ft.colors.INDIGO_700,
    "new_button_text": ft.colors.WHITE,
    "tabs_border": ft.colors.GREY_700,
    "tabs_text": ft.colors.GREY_400,
    "tabs_hover_text": ft.colors.GREY_200,
    "tab_active_border": ft.colors.INDIGO_500,
    "tab_active_text": ft.colors.INDIGO_400,
    "table_bg": ft.colors.GREY_800,
    "table_title": ft.colors.WHITE,
    "table_header_border": ft.colors.GREY_700,
    "table_header_bg": ft.colors.GREY_700,
    "table_header_text": ft.colors.GREY_300,
    "table_text_number": ft.colors.WHITE,
    "table_text_other": ft.colors.GREY_400,
    "table_divider": ft.colors.GREY_700,
    "table_empty": ft.colors.GREY_400,
    "badge_vigente_bg": ft.colors.GREEN_900,
    "badge_vigente_text": ft.colors.GREEN_300,
    "badge_a_vencer_bg": ft.colors.YELLOW_900,
    "badge_a_vencer_text": ft.colors.YELLOW_300,
    "badge_vencida_bg": ft.colors.RED_900,
    "badge_vencida_text": ft.colors.RED_300,
    "view_icon": ft.colors.INDIGO_400,
    "view_hover_icon": ft.colors.INDIGO_300,
    "edit_icon": ft.colors.GREY_400,
    "edit_hover_icon": ft.colors.GREY_300,
    "delete_icon": ft.colors.RED_400,
    "delete_hover_icon": ft.colors.RED_300,
}

def get_color(page: ft.Page, name: str):
    theme = LIGHT if page.theme_mode == ft.ThemeMode.LIGHT else DARK
    return theme[name]
