import flet as ft

# Base colors
WHITE = ft.colors.WHITE
PAGE_BG = "#F3F4F6"
CARD_BG = "#F8FAFC"

# Text colors
TEXT_DARK = "#111827"
TEXT_PRIMARY = "#1F2937"
TEXT_SECONDARY = "#6B7280"
TEXT_MUTED = "#374151"

# Button colors
PRIMARY_BG = "#3B82F6"
PRIMARY_TEXT = "#FFFFFF"
SECONDARY_TEXT = "#4B5563"
SECONDARY_BORDER = "#D1D5DB"
FOCUSED_BORDER = "#3B82F6"

# Neutral colors
GREY_LIGHT = "#E5E7EB"
GREY_DIVIDER = "#9CA3AF"
HEADER_BG = "#F9FAFB"

# Section colors
INDIGO = "#4F46E5"
INDIGO_BG = "#E0E7FF"
ORANGE = "#EA580C"
ORANGE_BG = "#FFEDD5"
TEAL = "#0F766E"
TEAL_BG = "#CCFBF1"

# Status colors
GREEN = "#16A34A"
GREEN_BG = "#D1FAE5"
GREEN_DARK = "#14532D"
YELLOW = "#CA8A04"
YELLOW_BG = "#FEF9C3"
YELLOW_DARK = "#713F12"
RED = "#DC2626"
RED_BG = "#FEE2E2"
RED_DARK = "#991B1B"
BLUE_HOVER = "#2563EB"
RESUMO_BG = "#EEF2FF"

# Semantic aliases
PRIMARY = ft.colors.BLUE
DANGER = ft.colors.RED
SUCCESS = ft.colors.GREEN
WARNING = ft.colors.ORANGE
OUTLINE = ft.colors.OUTLINE
